// src/remotion/compositions/ReelComposition.tsx
// Remotion Reel Composition — GSAP-driven vertical video (9:16)
// Renders based on GSAPManifest generated by the Motion Agent

import {
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  Easing,
  AbsoluteFill,
  Img,
  Video,
} from 'remotion';
import type { GSAPManifest, GSAPLayer } from '../../types/index.js';

interface CompositionProps {
  manifest: GSAPManifest;
  copyOutput?: {
    hook: string;
    cta?: string;
  };
}

// Map GSAP ease strings to Remotion's Easing module
function mapEasing(gsapEase: string): (t: number) => number {
  if (gsapEase.includes('power4')) return Easing.out(Easing.poly(4));
  if (gsapEase.includes('power2')) return Easing.out(Easing.poly(2));
  if (gsapEase.includes('expo')) return Easing.out(Easing.exp);
  if (gsapEase.includes('back')) return Easing.out(Easing.back(1.7));
  if (gsapEase.includes('sine')) return Easing.inOut(Easing.sin);
  if (gsapEase.includes('elastic')) return Easing.out(Easing.elastic(1));
  if (gsapEase.includes('circ')) return Easing.out(Easing.circle);
  return Easing.linear;  // linear fallback
}

interface AnimatedLayerProps {
  layer: GSAPLayer;
  fps: number;
}

function AnimatedLayer({ layer, fps }: AnimatedLayerProps) {
  const frame = useCurrentFrame();

  const delayFrames = Math.round((layer.animation.delay ?? 0) * fps);
  const durationFrames = Math.max(1, Math.round(layer.animation.duration * fps));
  const easingFn = mapEasing(layer.animation.ease);

  // Progress: 0 → 1 over the layer's entry animation window
  const progress = interpolate(
    frame,
    [delayFrames, delayFrames + durationFrames],
    [0, 1],
    {
      easing: easingFn,
      extrapolateLeft: 'clamp',
      extrapolateRight: 'clamp',
    }
  );

  const opacity = interpolate(progress, [0, 1], [0, layer.animation.opacity ?? 1]);
  const scale = interpolate(progress, [0, 1], [
    layer.animation.scale ? layer.animation.scale * 0.95 : 0.95,
    layer.animation.scale ?? 1,
  ]);

  // Text mask: translate from below (100% → 0%)
  const translateY = layer.animation.textMask
    ? interpolate(progress, [0, 1], [60, 0])
    : 0;

  const style: React.CSSProperties = {
    opacity,
    transform: `scale(${scale}) translateY(${translateY}px)`,
    overflow: layer.animation.textMask ? 'hidden' : 'visible',
  };

  if (layer.type === 'text') {
    return (
      <div style={{
        ...style,
        color: '#FFFFFF',
        fontSize: 64,
        fontFamily: '"Inter", "Helvetica Neue", sans-serif',
        fontWeight: 700,
        lineHeight: 1.15,
        padding: '0 60px',
        textAlign: 'center',
        position: 'absolute',
        width: '100%',
      }}>
        {layer.content}
      </div>
    );
  }

  if (layer.type === 'image' && layer.assetUrl) {
    return (
      <Img
        src={layer.assetUrl}
        style={{
          ...style,
          width: '100%',
          height: '100%',
          objectFit: 'cover',
        }}
      />
    );
  }

  if (layer.type === 'video' && layer.assetUrl) {
    return (
      <Video
        src={layer.assetUrl}
        style={{
          ...style,
          width: '100%',
          height: '100%',
          objectFit: 'cover',
        }}
        volume={1.0}
      />
    );
  }

  if (layer.type === 'shape') {
    return (
      <div style={{
        ...style,
        width: '100%',
        height: '100%',
        backgroundColor: '#000037',
      }} />
    );
  }

  return null;
}

export const ReelComposition: React.FC<CompositionProps> = ({ manifest }) => {
  const { fps } = useVideoConfig();

  return (
    <AbsoluteFill style={{ backgroundColor: '#000037', fontFamily: 'Inter, sans-serif' }}>
      {manifest.layers.map((layer) => (
        <AbsoluteFill key={layer.id} style={{ justifyContent: 'center', alignItems: 'center' }}>
          <AnimatedLayer layer={layer} fps={fps} />
        </AbsoluteFill>
      ))}
    </AbsoluteFill>
  );
};
